// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TerrabitTest.Data;

public partial class BankAccount
{
    public Guid Id { get; set; }

    public int AccountType { get; set; }

    public decimal Balance { get; set; }

    public DateTime OpenedDate { get; set; }

    public bool IsActive { get; set; }

    public bool IsDelete { get; set; }

    public DateTime CreateDate { get; set; }

    public DateTime UpdateDate { get; set; }

    public DateTime? DeleteDate { get; set; }

    public virtual ICollection<BankStatementHistory> BankStatementHistories { get; set; } = new List<BankStatementHistory>();

    public virtual User IdNavigation { get; set; }
}